# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Will\PythonProjects\lodging_repo\Qt_plugins\constants_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Constants_Dialog(object):
    def setupUi(self, Constants_Dialog):
        Constants_Dialog.setObjectName("Constants_Dialog")
        Constants_Dialog.resize(389, 260)
        self.gridLayout_2 = QtWidgets.QGridLayout(Constants_Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lodging_tax_edit = QtWidgets.QLineEdit(Constants_Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.lodging_tax_edit.sizePolicy().hasHeightForWidth())
        self.lodging_tax_edit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lodging_tax_edit.setFont(font)
        self.lodging_tax_edit.setObjectName("lodging_tax_edit")
        self.gridLayout.addWidget(self.lodging_tax_edit, 1, 1, 1, 1)
        self.aaa_discount_label = QtWidgets.QLabel(Constants_Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.aaa_discount_label.sizePolicy().hasHeightForWidth())
        self.aaa_discount_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.aaa_discount_label.setFont(font)
        self.aaa_discount_label.setObjectName("aaa_discount_label")
        self.gridLayout.addWidget(self.aaa_discount_label, 2, 0, 1, 1)
        self.sales_tax_edit = QtWidgets.QLineEdit(Constants_Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.sales_tax_edit.sizePolicy().hasHeightForWidth())
        self.sales_tax_edit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sales_tax_edit.setFont(font)
        self.sales_tax_edit.setObjectName("sales_tax_edit")
        self.gridLayout.addWidget(self.sales_tax_edit, 0, 1, 1, 1)
        self.lodging_tax_label = QtWidgets.QLabel(Constants_Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.lodging_tax_label.sizePolicy().hasHeightForWidth())
        self.lodging_tax_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lodging_tax_label.setFont(font)
        self.lodging_tax_label.setObjectName("lodging_tax_label")
        self.gridLayout.addWidget(self.lodging_tax_label, 1, 0, 1, 1)
        self.sales_tax_label = QtWidgets.QLabel(Constants_Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.sales_tax_label.sizePolicy().hasHeightForWidth())
        self.sales_tax_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.sales_tax_label.setFont(font)
        self.sales_tax_label.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.sales_tax_label.setScaledContents(False)
        self.sales_tax_label.setObjectName("sales_tax_label")
        self.gridLayout.addWidget(self.sales_tax_label, 0, 0, 1, 1)
        self.aaa_discount_edit = QtWidgets.QLineEdit(Constants_Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.aaa_discount_edit.sizePolicy().hasHeightForWidth())
        self.aaa_discount_edit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.aaa_discount_edit.setFont(font)
        self.aaa_discount_edit.setObjectName("aaa_discount_edit")
        self.gridLayout.addWidget(self.aaa_discount_edit, 2, 1, 1, 1)
        self.lbms_discount_label = QtWidgets.QLabel(Constants_Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.lbms_discount_label.sizePolicy().hasHeightForWidth())
        self.lbms_discount_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbms_discount_label.setFont(font)
        self.lbms_discount_label.setObjectName("lbms_discount_label")
        self.gridLayout.addWidget(self.lbms_discount_label, 3, 0, 1, 1)
        self.soe_commission_edit = QtWidgets.QLineEdit(Constants_Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.soe_commission_edit.sizePolicy().hasHeightForWidth())
        self.soe_commission_edit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.soe_commission_edit.setFont(font)
        self.soe_commission_edit.setObjectName("soe_commission_edit")
        self.gridLayout.addWidget(self.soe_commission_edit, 5, 1, 1, 1)
        self.expedia_discount_label = QtWidgets.QLabel(Constants_Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.expedia_discount_label.sizePolicy().hasHeightForWidth())
        self.expedia_discount_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.expedia_discount_label.setFont(font)
        self.expedia_discount_label.setObjectName("expedia_discount_label")
        self.gridLayout.addWidget(self.expedia_discount_label, 4, 0, 1, 1)
        self.expedia_commission_label = QtWidgets.QLabel(Constants_Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.expedia_commission_label.sizePolicy().hasHeightForWidth())
        self.expedia_commission_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.expedia_commission_label.setFont(font)
        self.expedia_commission_label.setObjectName("expedia_commission_label")
        self.gridLayout.addWidget(self.expedia_commission_label, 5, 0, 1, 1)
        self.soe_discount_edit = QtWidgets.QLineEdit(Constants_Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.soe_discount_edit.sizePolicy().hasHeightForWidth())
        self.soe_discount_edit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.soe_discount_edit.setFont(font)
        self.soe_discount_edit.setObjectName("soe_discount_edit")
        self.gridLayout.addWidget(self.soe_discount_edit, 4, 1, 1, 1)
        self.lbms_discount_edit = QtWidgets.QLineEdit(Constants_Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.lbms_discount_edit.sizePolicy().hasHeightForWidth())
        self.lbms_discount_edit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbms_discount_edit.setFont(font)
        self.lbms_discount_edit.setObjectName("lbms_discount_edit")
        self.gridLayout.addWidget(self.lbms_discount_edit, 3, 1, 1, 1)
        self.percent_label1 = QtWidgets.QLabel(Constants_Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.percent_label1.sizePolicy().hasHeightForWidth())
        self.percent_label1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.percent_label1.setFont(font)
        self.percent_label1.setObjectName("percent_label1")
        self.gridLayout.addWidget(self.percent_label1, 0, 2, 1, 1)
        self.percent_label2 = QtWidgets.QLabel(Constants_Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.percent_label2.sizePolicy().hasHeightForWidth())
        self.percent_label2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.percent_label2.setFont(font)
        self.percent_label2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.percent_label2.setObjectName("percent_label2")
        self.gridLayout.addWidget(self.percent_label2, 1, 2, 1, 1)
        self.percent_label3 = QtWidgets.QLabel(Constants_Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.percent_label3.sizePolicy().hasHeightForWidth())
        self.percent_label3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.percent_label3.setFont(font)
        self.percent_label3.setObjectName("percent_label3")
        self.gridLayout.addWidget(self.percent_label3, 2, 2, 1, 1)
        self.percent_label4 = QtWidgets.QLabel(Constants_Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.percent_label4.sizePolicy().hasHeightForWidth())
        self.percent_label4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.percent_label4.setFont(font)
        self.percent_label4.setObjectName("percent_label4")
        self.gridLayout.addWidget(self.percent_label4, 3, 2, 1, 1)
        self.percent_label5 = QtWidgets.QLabel(Constants_Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.percent_label5.sizePolicy().hasHeightForWidth())
        self.percent_label5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.percent_label5.setFont(font)
        self.percent_label5.setObjectName("percent_label5")
        self.gridLayout.addWidget(self.percent_label5, 4, 2, 1, 1)
        self.percent_label6 = QtWidgets.QLabel(Constants_Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.percent_label6.sizePolicy().hasHeightForWidth())
        self.percent_label6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.percent_label6.setFont(font)
        self.percent_label6.setObjectName("percent_label6")
        self.gridLayout.addWidget(self.percent_label6, 5, 2, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setColumnStretch(2, 1)
        self.gridLayout.setRowStretch(0, 1)
        self.gridLayout.setRowStretch(1, 1)
        self.gridLayout.setRowStretch(2, 1)
        self.gridLayout.setRowStretch(3, 1)
        self.gridLayout.setRowStretch(4, 1)
        self.gridLayout.setRowStretch(5, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.save_button = QtWidgets.QPushButton(Constants_Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.save_button.sizePolicy().hasHeightForWidth())
        self.save_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.save_button.setFont(font)
        self.save_button.setObjectName("save_button")
        self.horizontalLayout.addWidget(self.save_button)
        self.close_button = QtWidgets.QPushButton(Constants_Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.close_button.sizePolicy().hasHeightForWidth())
        self.close_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.close_button.setFont(font)
        self.close_button.setObjectName("close_button")
        self.horizontalLayout.addWidget(self.close_button)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 1)

        self.retranslateUi(Constants_Dialog)
        QtCore.QMetaObject.connectSlotsByName(Constants_Dialog)
        Constants_Dialog.setTabOrder(self.sales_tax_edit, self.lodging_tax_edit)
        Constants_Dialog.setTabOrder(self.lodging_tax_edit, self.aaa_discount_edit)
        Constants_Dialog.setTabOrder(self.aaa_discount_edit, self.lbms_discount_edit)
        Constants_Dialog.setTabOrder(self.lbms_discount_edit, self.soe_discount_edit)
        Constants_Dialog.setTabOrder(self.soe_discount_edit, self.soe_commission_edit)
        Constants_Dialog.setTabOrder(self.soe_commission_edit, self.save_button)
        Constants_Dialog.setTabOrder(self.save_button, self.close_button)

    def retranslateUi(self, Constants_Dialog):
        _translate = QtCore.QCoreApplication.translate
        Constants_Dialog.setWindowTitle(_translate("Constants_Dialog", "Constants"))
        self.lodging_tax_edit.setText(_translate("Constants_Dialog", "2.50"))
        self.aaa_discount_label.setText(_translate("Constants_Dialog", "AAA Discount"))
        self.sales_tax_edit.setText(_translate("Constants_Dialog", "15.25"))
        self.lodging_tax_label.setText(_translate("Constants_Dialog", "Lodging Tax"))
        self.sales_tax_label.setText(_translate("Constants_Dialog", "Sales Tax"))
        self.lbms_discount_label.setText(_translate("Constants_Dialog", "Manager's Special"))
        self.expedia_discount_label.setText(_translate("Constants_Dialog", "Expedia Discount"))
        self.expedia_commission_label.setText(_translate("Constants_Dialog", "Expedia Commission"))
        self.close_button.setText(_translate("Constants_Dialog", "Close"))
        self.save_button.setText(_translate("Constants_Dialog", "Save"))
