# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Will\PythonProjects\lodging_repo\Qt_plugins\lodging_calculator_qt.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Rate_Calculator(object):
    def setupUi(self, Rate_Calculator):
        Rate_Calculator.setObjectName("Rate_Calculator")
        Rate_Calculator.resize(637, 363)
        self.centralwidget = QtWidgets.QWidget(Rate_Calculator)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.calculator_frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.calculator_frame.sizePolicy().hasHeightForWidth())
        self.calculator_frame.setSizePolicy(sizePolicy)
        self.calculator_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.calculator_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.calculator_frame.setObjectName("calculator_frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.calculator_frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.rack_rate_edit = QtWidgets.QLineEdit(self.calculator_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rack_rate_edit.sizePolicy().hasHeightForWidth())
        self.rack_rate_edit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.rack_rate_edit.setFont(font)
        self.rack_rate_edit.setObjectName("rack_rate_edit")
        self.gridLayout.addWidget(self.rack_rate_edit, 1, 1, 1, 1)
        self.aaa_rate_edit = QtWidgets.QLineEdit(self.calculator_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.aaa_rate_edit.sizePolicy().hasHeightForWidth())
        self.aaa_rate_edit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.aaa_rate_edit.setFont(font)
        self.aaa_rate_edit.setClearButtonEnabled(False)
        self.aaa_rate_edit.setObjectName("aaa_rate_edit")
        self.gridLayout.addWidget(self.aaa_rate_edit, 2, 1, 1, 1)
        self.aaa_total_edit = QtWidgets.QLineEdit(self.calculator_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.aaa_total_edit.sizePolicy().hasHeightForWidth())
        self.aaa_total_edit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.aaa_total_edit.setFont(font)
        self.aaa_total_edit.setObjectName("aaa_total_edit")
        self.gridLayout.addWidget(self.aaa_total_edit, 2, 2, 1, 1)
        self.aaa_label = QtWidgets.QLabel(self.calculator_frame)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.aaa_label.setFont(font)
        self.aaa_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.aaa_label.setObjectName("aaa_label")
        self.gridLayout.addWidget(self.aaa_label, 2, 0, 1, 1)
        self.lbms_rate_edit = QtWidgets.QLineEdit(self.calculator_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbms_rate_edit.sizePolicy().hasHeightForWidth())
        self.lbms_rate_edit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lbms_rate_edit.setFont(font)
        self.lbms_rate_edit.setObjectName("lbms_rate_edit")
        self.gridLayout.addWidget(self.lbms_rate_edit, 3, 1, 1, 1)
        self.rack_total_edit = QtWidgets.QLineEdit(self.calculator_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rack_total_edit.sizePolicy().hasHeightForWidth())
        self.rack_total_edit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.rack_total_edit.setFont(font)
        self.rack_total_edit.setObjectName("rack_total_edit")
        self.gridLayout.addWidget(self.rack_total_edit, 1, 2, 1, 1)
        self.lbms_total_edit = QtWidgets.QLineEdit(self.calculator_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbms_total_edit.sizePolicy().hasHeightForWidth())
        self.lbms_total_edit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lbms_total_edit.setFont(font)
        self.lbms_total_edit.setObjectName("lbms_total_edit")
        self.gridLayout.addWidget(self.lbms_total_edit, 3, 2, 1, 1)
        self.rack_label = QtWidgets.QLabel(self.calculator_frame)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.rack_label.setFont(font)
        self.rack_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.rack_label.setObjectName("rack_label")
        self.gridLayout.addWidget(self.rack_label, 1, 0, 1, 1)
        self.soe_label = QtWidgets.QLabel(self.calculator_frame)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.soe_label.setFont(font)
        self.soe_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.soe_label.setObjectName("soe_label")
        self.gridLayout.addWidget(self.soe_label, 4, 0, 1, 1)
        self.soe_rate_edit = QtWidgets.QLineEdit(self.calculator_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.soe_rate_edit.sizePolicy().hasHeightForWidth())
        self.soe_rate_edit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.soe_rate_edit.setFont(font)
        self.soe_rate_edit.setObjectName("soe_rate_edit")
        self.gridLayout.addWidget(self.soe_rate_edit, 4, 1, 1, 1)
        self.lbms_label = QtWidgets.QLabel(self.calculator_frame)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lbms_label.setFont(font)
        self.lbms_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbms_label.setObjectName("lbms_label")
        self.gridLayout.addWidget(self.lbms_label, 3, 0, 1, 1)
        self.total_label = QtWidgets.QLabel(self.calculator_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.total_label.sizePolicy().hasHeightForWidth())
        self.total_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.total_label.setFont(font)
        self.total_label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.total_label.setObjectName("total_label")
        self.gridLayout.addWidget(self.total_label, 0, 2, 1, 1)
        self.soe_total_edit = QtWidgets.QLineEdit(self.calculator_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.soe_total_edit.sizePolicy().hasHeightForWidth())
        self.soe_total_edit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.soe_total_edit.setFont(font)
        self.soe_total_edit.setObjectName("soe_total_edit")
        self.gridLayout.addWidget(self.soe_total_edit, 4, 2, 1, 1)
        self.rate_label = QtWidgets.QLabel(self.calculator_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.rate_label.sizePolicy().hasHeightForWidth())
        self.rate_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.rate_label.setFont(font)
        self.rate_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.rate_label.setScaledContents(True)
        self.rate_label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.rate_label.setObjectName("rate_label")
        self.gridLayout.addWidget(self.rate_label, 0, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 2)
        self.gridLayout.setColumnStretch(2, 2)
        self.gridLayout.setRowStretch(0, 1)
        self.gridLayout.setRowStretch(1, 2)
        self.gridLayout.setRowStretch(2, 2)
        self.gridLayout.setRowStretch(3, 2)
        self.gridLayout.setRowStretch(4, 2)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.clear_button = QtWidgets.QPushButton(self.calculator_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clear_button.sizePolicy().hasHeightForWidth())
        self.clear_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.clear_button.setFont(font)
        self.clear_button.setObjectName("clear_button")
        self.horizontalLayout.addWidget(self.clear_button)
        self.calculate_button = QtWidgets.QPushButton(self.calculator_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calculate_button.sizePolicy().hasHeightForWidth())
        self.calculate_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.calculate_button.setFont(font)
        self.calculate_button.setObjectName("calculate_button")
        self.horizontalLayout.addWidget(self.calculate_button)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.gridLayout_3.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.calculator_frame, 0, 0, 1, 1)
        Rate_Calculator.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Rate_Calculator)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 637, 26))
        self.menubar.setObjectName("menubar")
        self.configure_menu = QtWidgets.QMenu(self.menubar)
        self.configure_menu.setObjectName("configure_menu")
        Rate_Calculator.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Rate_Calculator)
        self.statusbar.setObjectName("statusbar")
        Rate_Calculator.setStatusBar(self.statusbar)
        self.constants_action = QtWidgets.QAction(Rate_Calculator)
        self.constants_action.setObjectName("constants_action")
        self.configure_menu.addAction(self.constants_action)
        self.menubar.addAction(self.configure_menu.menuAction())

        self.retranslateUi(Rate_Calculator)
        self.clear_button.clicked.connect(self.rack_rate_edit.clear)
        self.clear_button.clicked.connect(self.rack_total_edit.clear)
        self.clear_button.clicked.connect(self.aaa_rate_edit.clear)
        self.clear_button.clicked.connect(self.aaa_total_edit.clear)
        self.clear_button.clicked.connect(self.lbms_rate_edit.clear)
        self.clear_button.clicked.connect(self.lbms_total_edit.clear)
        self.clear_button.clicked.connect(self.soe_rate_edit.clear)
        self.clear_button.clicked.connect(self.soe_total_edit.clear)
        QtCore.QMetaObject.connectSlotsByName(Rate_Calculator)
        Rate_Calculator.setTabOrder(self.rack_rate_edit, self.rack_total_edit)
        Rate_Calculator.setTabOrder(self.rack_total_edit, self.aaa_rate_edit)
        Rate_Calculator.setTabOrder(self.aaa_rate_edit, self.aaa_total_edit)
        Rate_Calculator.setTabOrder(self.aaa_total_edit, self.lbms_rate_edit)
        Rate_Calculator.setTabOrder(self.lbms_rate_edit, self.lbms_total_edit)
        Rate_Calculator.setTabOrder(self.lbms_total_edit, self.soe_rate_edit)
        Rate_Calculator.setTabOrder(self.soe_rate_edit, self.soe_total_edit)
        Rate_Calculator.setTabOrder(self.soe_total_edit, self.clear_button)
        Rate_Calculator.setTabOrder(self.clear_button, self.calculate_button)

    def retranslateUi(self, Rate_Calculator):
        _translate = QtCore.QCoreApplication.translate
        Rate_Calculator.setWindowTitle(_translate("Rate_Calculator", "Lodging Calculator"))
        self.aaa_label.setText(_translate("Rate_Calculator", "AAA"))
        self.rack_label.setText(_translate("Rate_Calculator", "RACK"))
        self.soe_label.setText(_translate("Rate_Calculator", "SOE"))
        self.lbms_label.setText(_translate("Rate_Calculator", "LBMS"))
        self.total_label.setText(_translate("Rate_Calculator", "Total"))
        self.rate_label.setText(_translate("Rate_Calculator", "Rate"))
        self.clear_button.setText(_translate("Rate_Calculator", "Clear"))
        self.calculate_button.setText(_translate("Rate_Calculator", "Calculate"))
        self.configure_menu.setTitle(_translate("Rate_Calculator", "&Configure"))
        self.constants_action.setText(_translate("Rate_Calculator", "&Constants"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Rate_Calculator = QtWidgets.QMainWindow()
    ui = Ui_Rate_Calculator()
    ui.setupUi(Rate_Calculator)
    Rate_Calculator.show()
    sys.exit(app.exec_())

